name: lab1

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build1
      run: |
        cd lab1/
        make lab1test
        ./test
        
    - name: Build2
      run: |
        cd lab2/2_1
        make lab2.1test
        ./test
        cd ../Lab2_2_6 
        make lab1tes 
        ./test
