name: lab1

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cool
      uses: actions/checkout@v2
    
    - name: make
      run: |
        cd lab1/
          make lab1test
          ./test
