name: lab1

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build1
      run: |
        cd lab1/
        make lab1test
        ./test
        
    - name: Build2
      run: |
        cd lab2/2_1
        make lab2_1test
        ./test
        cd ../2_2_6 
        make lab1test 
        ./test
        
    - name: Build3
      run: |
        cd lab3/
        make lab3test
        ./test
        
    - name: Build41
      run: |
        cd 41
        make lab41test
        ./test
        
    - name: Build42
      run: |
        cd 42
        make lab42test
        ./test
        
    - name: Build5
      run: |
        cd lab5
        make lab5test
        ./test
        
    - name: Build6
      run: |
        cd lab6
        make lab6test
        ./test
        
    - name: Build7
      run: |
        cd lab7
        make lab7test
        ./test
        make checkCov
