name: lab2

on:
  push:
    branches: [ lab2 ]
  pull_request:
    branches: [ lab2 ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        cd lab1/ 
          make maintest
          ./test
