name: buildandtest

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkoutcode
      
        uses: actions/checkout@v2
        
      - run: |
          cd lab1/
          make maintest
          ./maintest
